export {
  WORD_REFERENCE_LIMITS,
  WORD_REFERENCE_MODE,
  WORD_REFERENCE_PROTOCOL,
  normalizeWordName,
  resolveWordReference,
  type ExactNameResolutionInput,
  type ResolvedWordMeaning,
  type ResolvedWordReference,
  type WordMeaningRecordInput,
  type WordReferenceInput,
  type WordReferenceResolution,
  type WordReferenceSourceInput,
  type WordReferenceTrust,
  type WordReferenceVerification,
} from "./reference.js";

export {
  WORD_BROWSER_HANDOFF_LIMITS,
  WORD_BROWSER_HANDOFF_PROTOCOL,
  WordBrowserHandoffError,
  WordBrowserSession,
  type WordBrowserHandoffErrorCode,
  type WordBrowserMeaningProvenance,
  type WordBrowserOffer,
  type WordBrowserOfferedMeaning,
  type WordBrowserOfferedReference,
  type WordBrowserOpenReceipt,
  type WordBrowserPlan,
  type WordBrowserPlanReceipt,
  type WordBrowserPort,
  type WordBrowserSelectedReference,
  type WordBrowserSelectionReceipt,
  type WordBrowserSessionOptions,
} from "./browser-handoff.js";
